### PR TITLE
Input sanitization

### PR DESCRIPTION
**Pull request by rubenmartinez-alm**
As recommended by github, I am proposing this change to sanitize inputs that are used directly as part of shell commands, and could be used to execute anything in the runner (I know it is not likely to happen but just to follow good practices 😊)

I could execute a couple of arbitrary commands with the following test:

image

Then, as you can see in the job log:

image

Workflow in text for copy-paste:
```
name: test-clair-scan-action

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Test Clair Scan
      uses: santander-group/clair-scan-action@09ad8311ea3ebd4744dc84e9ba9b6992c4b9b16d
      with:
        clair_timeout: '120; echo "Doing bad things now..."; curl -k "https://www.google.com"'
        report_path: 'whatever; echo "Doing more bad things now..."'
```

### CODE REVIEW

**Comment by rubenmartinez-alm** [comment]
Pending passing this tests https://github.com/the-iron-bank-of-braavos/clair-workflow-test/commit/9be7ec881219ce4602178c13168618ebb899139c, thanks to @dhernandez-cto for the catch

**Comment by rubenmartinez-alm** [comment]
Seeing the latest errors we found, it seems they happened both in the PR branch and also in the main branch (as you also suggested it might happen)

I mean at: https://github.com/the-iron-bank-of-braavos/clair-workflow-test/actions
image
the second commit [92d541](https://github.com/the-iron-bank-of-braavos/clair-workflow-test/commit/92d541ce0f9d50637d712c1683eef6247328a3b8) looks like it was executed with mean

So I have executed tests on my own repo in my own repo, and the "local" jobs executed correctly (the "remote" ones didn't execute successfully because I didn't have the secrets on my repo):

https://github.com/rubenmartinez-alm/clair-workflow-test/actions/runs/1212799355

I used my own repo, since I cannot create branches at https://github.com/the-iron-bank-of-braavos/clair-workflow-test:
```
❯ git push --set-upstream origin test-pr-input-sanitization
ERROR: Permission to the-iron-bank-of-braavos/clair-workflow-test.git denied to rubenmartinez-alm.
fatal: Could not read from remote repository.
```
If you give me permissions I can continue tests there.

**Comment by rubenmartinez-alm** [comment]
In summary :D 

- if you give me permissions to push branches on https://github.com/the-iron-bank-of-braavos/clair-workflow-test, I can do some tests there
- Otherwise, if you want to validate the PR, I did some local tests and they worked fine

**Comment by rubenmartinez-alm** [comment]
Tests look good:

https://github.com/the-iron-bank-of-braavos/clair-workflow-test/runs/3543735950?check_suite_focus=true

**Comment by rubenmartinez-alm** [comment]
Thanks David for spotting the bugs in the PR :)

**Review by dhernandez-cto — APPROVED** [review]
Great Job! Now we are a little bit more secure.

**Pull request merged**
